
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
    }
}

dependencies {
    implementation project(':smali-lib:util')
    api project(':smali-lib:dexlib2')
    implementation depends.jcommander

    testImplementation depends.junit
    testImplementation project(':smali-lib:smali')
    testImplementation depends.antlr_runtime
}

processResources.inputs.property('version', version)
processResources.expand('version': version)

// Build a separate jar that contains all dependencies
task fatJar(type: Jar, dependsOn: [':smali-lib:util:jar', ':smali-lib:dexlib2:jar']) {
    from sourceSets.main.output
    from { configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) } }

    archiveClassifier.set('fat')

    manifest {
        attributes('Main-Class': 'org.jf.baksmali.Main')
    }

    doLast {
        if (!System.getProperty('os.name').toLowerCase().contains('windows')) {
            ant.symlink(link: file("${destinationDirectory.get()}/baksmali.jar"), resource: archiveFile.get().getAsFile(), overwrite: true)
        }
    }
}
tasks.getByPath('build').dependsOn(fatJar)


task fastbuild(dependsOn: build) {
}

task fb(dependsOn: fastbuild) {
}

tasks.getByPath('javadoc').onlyIf({
    !gradle.taskGraph.hasTask(fastbuild)
})

tasks.getByPath('test').onlyIf({
    !gradle.taskGraph.hasTask(fastbuild)
})